### ISSUE TITLE
delete/2 cannot delete empty path

### ISSUE THREAD

**Issue by heyoka** [nalundgaard/jsn#42]
When trying to delete an empty object (value is an empty map), jsn does not delete it:

`jsn:delete(<<"data">>, #{<<"data">> => #{}, <<"var">> => 1}).`
results in
`#{<<"data">> => #{},<<"var">> => 1}`
expected
`#{<<"var">> => 1}`

but without/2 can do it:
`jsn:without([<<"data">>], #{<<"data">> => #{}, <<"var">> => 1}).`
results in
`#{<<"var">> => 1}`

**Comment by nalundgaard** [comment]
Interesting catch. The bug is [jsn.erl#L992](https://github.com/nalundgaard/jsn/blob/cb0aaaf/src/jsn.erl#L992-L993):

```erlang
 	        E when Value =:= jsn__delete, (E =:= jsn__undefined orelse E =:= Empty) ->
	            return_if_object(Object, Empty);
```

I think an additional condition `Rest =/= []` should cover this case here:

```erlang
 	        E when Value =:= jsn__delete, Rest =/= [], (E =:= jsn__undefined orelse E =:= Empty) ->
	            return_if_object(Object, Empty);
```

Then we just need to add a unit test or two to [`jsn_tests:delete_test_/0`](https://github.com/nalundgaard/jsn/blob/cb0aaaf25c3c55e37bbf3bb4e3c8656858b8de59/test/jsn_tests.erl#L288-L322). I can do this when I have some spare time, or if you would like to contribute, that would be welcome as well!

**Comment by nalundgaard** [comment]
@heyoka Have a look at https://github.com/nalundgaard/jsn/pull/43.

**Comment by heyoka** [comment]
@nalundgaard looks good, thx
Now it is too late to contribute, I guess ? Maybe next time :)

**Comment by nalundgaard** [comment]
> Now it is too late to contribute, I guess ? Maybe next time :)

Sorry! Yes, next time, I think.
