### ISSUE TITLE
How is set supposed to work ?

### ISSUE THREAD

**Issue by heyoka** [nalundgaard/jsn#45]
Hi,
so I use `jsn:set` to set insert/update values in a jsn structure, this works well:

```erl
%% insert
jsn:set(<<"data.fup">>, #{<<"data">> => #{<<"foo">> => <<"bar">>}}, <<"fop">>).
%% insert gives
#{<<"data">> =>
      #{<<"foo">> => <<"bar">>,<<"fup">> => <<"fop">>}}
```

```erl
%% update
jsn:set(<<"data.foo">>, #{<<"data">> => #{<<"foo">> => <<"bar">>}}, <<"fop">>).
%% update gives
#{<<"data">> => #{<<"foo">> => <<"fop">>}}
```

**but**
```erl
%% update
jsn:set(<<"data.foo.far">>, #{<<"data">> => #{<<"foo">> => <<"bar">>}}, <<"fop">>).
%% gives
** exception error: no function clause matching jsn:keys_set([<<"far">>],<<"bar">>,<<"fop">>,#{}) 
   (...../jsn/src/jsn.erl, line 983) in function  jsn:keys_set/4 (....../jsn/src/jsn.erl, line 998)

```

question: what is the intended behaviour here, should it be possible to update a path with a deeper value ?

thx

**Comment by nalundgaard** [comment]
The intent is definitely to support updating a path with a deeper value when it is possible to do _non-destructively_, as in your first two examples. In the last one, you're telling it to set the key `"far"` in object `"bar"` to `"fop"`. Since `"bar"` is a string and not an object, it is rejected. We cannot perform this insertion without erasing `"bar"` and replacing it with an empty object to set. I think that would count as extremely unexpected behavior for a library, so I feel pretty reticent about it. It could be that we should add `Options` here to support overwriting existing values, and perhaps also raise a better exception here, but the failure is very much intentional.

**Comment by heyoka** [comment]
On a second thought, it would really be unexpected behavior. It would just come in handy for my data-flow application where I have a 'set' node that sets values even if they already exist (there is also a 'default 'node, which only sets values, if the path does not already exist). 
I'll have to decide if I will go with making it impossible to do a path-desctructive call to 'set' or deleting the path that would be overwritten beforehand.

Thank you!
